module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      Crust: "#11111b",
      Mantle: "#181825",
      Base: "#1e1e2e",
      Surface0: "#313244",
      Surface1: "#45475a",
      Surface2: "#585b70",
      Overlay0: "#6c7086",
      Overlay1: "#7f849c",
      Overlay2: "#9399b2",
      Subtext0: "#a6adc8",
      Subtext1: "#bac2de",
      text: "#cdd6f4",
      colors: {
        Lavender: "#b4befe",
        Blue: "#89b4fa",
        Sapphire: "#74c7ec",
        Sky: "#89dceb",
        Teal: "#94e2d5",
        Green: "#a6e3a1",
        Yellow: "#f9e2af",
        Peach: "#fab387",
        Maroon: "#eba0ac",
        Red: "#f38ba8",
        Mauve: "#cba6f7",
        Pink: "#f5c2e7",
        Flamingo: "#f2cdcd",
        Rosewater: "#f5e0dc",
      },
    },
    fontFamily: {
      mono: ["JetBrains Mono", "monospace"],
    },
    extend: {},
  },
  plugins: [],
};
